# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  config.vm.provider 'virtualbox' do |vb|
   vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
  end  

  # config.vm.provision "shell" ,path:"../script/install.sh"

  config.vm.box = "zhaoyunxing/docker"
  config.vm.box_version = "1.8"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  # master node syn
  config.vm.define "kube-master" do |master|

    master.vm.hostname = "kube-master"
    master.vm.network "private_network", ip: "192.168.56.100"

    # master.vm.provision "shell" ,path:"../script/master-init.sh"

    master.vm.provider "virtualbox" do |vb|
     vb.cpus=2
     vb.memory = "3072"
     vb.name="kube-master"
    end

  end

  # work node
  (1..2).each do |i|
    config.vm.define "node#{i}" do |node|

      node.vm.hostname = "kube-node#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{i+100}"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.name = "kube-node#{i}"
      end
    end
  end

end
