apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-wn5fj
    field.cattle.io/publicEndpoints: '[{"addresses":["172.16.254.41"],"port":31520,"protocol":"TCP","serviceName":"public:zookeeper-nodeport","allNodes":true}]'
  creationTimestamp: "2020-01-08T07:45:02Z"
  generation: 2
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-public-zookeeper
  name: zookeeper
  namespace: public
  resourceVersion: "621940"
  selfLink: /apis/apps/v1/namespaces/public/deployments/zookeeper
  uid: c7360639-31ea-11ea-9248-000c2936cea7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-public-zookeeper
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-01-08T07:45:02Z"
        field.cattle.io/ports: '[[{"containerPort":2181,"dnsName":"zookeeper-nodeport","kind":"NodePort","name":"2181tcp01","protocol":"TCP"}]],[[{"containerPort":2888,"dnsName":"zookeeper-nodeport","kind":"NodePort","name":"2888tcp02","protocol":"TCP"}]],[[{"containerPort":3888,"dnsName":"zookeeper-nodeport","kind":"NodePort","name":"3888tcp03","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-public-zookeeper
    spec:
      containers:
      - image: wurstmeister/zookeeper
        imagePullPolicy: Always
        name: zookeeper
        ports:
        - containerPort: 2181
          name: 2181tcp01
          protocol: TCP
        - containerPort: 2888
          name: 2888tcp02
          protocol: TCP
        - containerPort: 3888
          name: 3888tcp03
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-08T07:56:07Z"
    lastUpdateTime: "2020-01-08T07:56:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-08T07:56:07Z"
    lastUpdateTime: "2020-01-08T07:56:07Z"
    message: ReplicaSet "zookeeper-d96985449" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1